### ISSUE TITLE
读数据库时，偶尔会出现Cannot Open when State is Connecting这种错

### ISSUE THREAD

**Issue by taylor1102** [VictorTzeng/Zxw.Framework.NetCore#25]
异常日志：
*——*——*——*——*——*——Begin——*——*——*——*——*——*
记录时间：2018-08-15 16:49:20,651
线程ID：49
日志等级：ERROR
日志类型：Hlb.Robin.Filters.GlobalExceptionFilter
Error
*——*——*——*——*——*——E n d——*——*——*——*——*——*
System.InvalidOperationException: Cannot Open when State is Connecting.
   at MySql.Data.MySqlClient.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken)
   at MySql.Data.MySqlClient.MySqlConnection.Open() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 157
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider._FastQuery[TEntity](RelationalQueryContext relationalQueryContext, ShaperCommandContext shaperCommandContext, Func`3 materializer, Type contextType, IDiagnosticsLogger`1 logger)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Hlb.Robin.Website.Controllers.ArticleController.Index(String type, Int32 page) in D:\Controllers\ArticleController.cs:line 28
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
*——*——*——*——*——*——Begin——*——*——*——*——*——*
记录时间：2018-08-15 16:49:21,278
线程ID：51
日志等级：ERROR
日志类型：Hlb.Robin.Filters.GlobalExceptionFilter
Error
*——*——*——*——*——*——E n d——*——*——*——*——*——*
System.InvalidOperationException: Cannot set MySqlCommand.CommandText when there is an open DataReader for this command; it must be closed first.
   at MySql.Data.MySqlClient.MySqlCommand.set_CommandText(String value) in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlCommand.cs:line 94
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.CreateCommand(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.Execute(IRelationalConnection connection, DbCommandMethod executeMethod, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Storage.Internal.RelationalCommand.ExecuteReader(IRelationalConnection connection, IReadOnlyDictionary`2 parameterValues)
   at Microsoft.EntityFrameworkCore.Query.QueryMethodProvider._FastQuery[TEntity](RelationalQueryContext relationalQueryContext, ShaperCommandContext shaperCommandContext, Func`3 materializer, Type contextType, IDiagnosticsLogger`1 logger)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Hlb.Robin.Website.Controllers.ArticleController.Index(String type, Int32 page) in D:\Controllers\ArticleController.cs:line 28
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()

**Comment by VictorTzeng** [comment]
你从nuget更新到最新beta版，然后参照demo注入dbcontext试试看

**Comment by taylor1102** [comment]
更新了，用的就是demo的注入方式 还是会报：当此命令有一个打开的DataReader时，无法设置MySqlCommand.CommandText; 它必须先关闭。
是不是有的时候查询完没有关闭DataReader

**Comment by VictorTzeng** [comment]
要看下你具体代码才知道，很少用mysql。可以先去逛下国际论坛，哈哈

**Comment by mazhongbin** [comment]
我也遇到了一样的问题，在使用mysql的时候，在一个方法中查询两个表，然后把一张表查询的结果作为条件在另一张表中进行查询，就会出现上面的错误，查了资料，说是延时查询的问题，第一个查询打开一个DataReader没有关闭，所有第二次查询就报错了，关键是mysql不支持同时打开两个DataReader，sqlserver通过连接字符串配置支持同时打开两个DataReader，所以不会报错。

**Comment by VictorTzeng** [comment]
嗯，谢谢反馈，在下个版本中会修复。或者可以把你的解决方案推上来

**Comment by mazhongbin** [comment]
> 嗯，谢谢反馈，在下个版本中会修复。或者可以把你的解决方案推上来

https://github.com/PomeloFoundation/Pomelo.EntityFrameworkCore.MySql/issues/85
好像这个问题，官方也没好的解决方案，我也没找到。

**Comment by VictorTzeng** [comment]
那就只能等柚子大人先修复了来。。
