### ISSUE TITLE
缓存拦截器使用异步时报错

### ISSUE THREAD

**Issue by wannvmi** [VictorTzeng/Zxw.Framework.NetCore#39]
```
AspectCore.DynamicProxy.AspectInvocationException: Exception has been thrown by the aspect of an invocation. ---> Object reference not set to an instance of an object.. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at ActualCombat.Hotel.Core.Attributes.RedisCacheAttribute.Invoke(AspectContext context, AspectDelegate next) in E:\Git\src\Hotel.Core\Attributes\RedisCacheAttribute.cs:line 61
   at AspectCore.DynamicProxy.AspectActivator.InvokeTask[TResult](AspectActivatorContext activatorContext)
   --- End of inner exception stack trace ---
   at AspectCore.DynamicProxy.AspectActivator.InvokeTask[TResult](AspectActivatorContext activatorContext)
   at ActualCombat.Hotel.Api.Controllers.UserController.SelectStudentByClassIdAsync() in 
   E:\Git\src\Hotel.Core.Api\Controllers\UserController.cs:line 37
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextExceptionFilterAsync()
```

**Comment by VictorTzeng** [comment]
收到，谢谢反馈，我周末调试一下

**Comment by wannvmi** [comment]
作者 我找到了一个解决办法
为什么实现的原因我不清楚 但是问题却解决了
代码如下：
## RedisCacheAttribute.cs
```
                var key = string.IsNullOrEmpty(CacheKey)
                    ? new CacheKey(context.ServiceMethod, parameters, context.Parameters).GetRedisCacheKey()
                    : CacheKey;
                var value = await DistributedCacheManager.GetAsync(key);
                if (value != null)
                {
                    if (context.ServiceMethod.IsReturnTask())
                    {
                        //context.ReturnValue = Task.FromResult(JsonConvert.DeserializeObject(value,
                        //    context.ServiceMethod.ReturnType.GenericTypeArguments[0]));
                        dynamic dynamicValue = JsonConvert.DeserializeObject(value, context.ServiceMethod.ReturnType.GenericTypeArguments[0]);
                        context.ReturnValue = Task.FromResult(dynamicValue);
                    }
                    else
                    {
                        context.ReturnValue = JsonConvert.DeserializeObject(value, context.ServiceMethod.ReturnType);
                    }
                }
                else
                {
                    await context.Invoke(next);
                    object returnValue = context.ReturnValue;
                    if (context.ServiceMethod.IsReturnTask())
                    {
                        //returnValue = returnValue.GetType().GetField("Result").GetValue(returnValue);
                        dynamic dynamicValue = returnValue;
                        returnValue = dynamicValue.Result;          
                    }
                    await DistributedCacheManager.SetAsync(key, returnValue, Expiration * 60);
                    //await next(context);
                }
```
## MemoryCacheAttribute.cs
```
                var key = string.IsNullOrEmpty(CacheKey)
                    ? new CacheKey(context.ServiceMethod, parameters, context.Parameters).GetMemoryCacheKey()
                    : CacheKey;
                if (_cache.TryGetValue(key, out object value))
                {
                    if (context.ServiceMethod.IsReturnTask())
                    {
                        //context.ReturnValue = Task.FromResult(value);
                        dynamic dynamicValue = value;
                        context.ReturnValue = Task.FromResult(dynamicValue);
                    }
                    else
                    {
                        context.ReturnValue = value;
                    }
                }
                else
                {
                    await context.Invoke(next);
                    object returnValue = context.ReturnValue;
                    if (context.ServiceMethod.IsReturnTask())
                    {
                        //returnValue = returnValue.GetType().GetField("Result").GetValue(returnValue);
                        dynamic dynamicValue = returnValue;
                        returnValue = dynamicValue.Result;
                    }

                    _cache.Set(key, returnValue, new MemoryCacheEntryOptions()
                    {
                        AbsoluteExpirationRelativeToNow = TimeSpan.FromMinutes(Expiration)
                    });
                    //await next(context);
                }
``` 
![TIM截图20190621101503](https://user-images.githubusercontent.com/37651498/59892874-7c281c80-940d-11e9-9f98-f9aef20c872f.jpg)

**Comment by VictorTzeng** [comment]
嗯，之前处理过，不过是另一个库[AspectCore.Extensions.Cache](https://github.com/VictorTzeng/AspectCore.Extensions.Cache/blob/master/src/AspectCore.Extensions.Cache/AspectCore.Extensions.Cache/RedisCacheAttribute.cs) 

我同步一下代码

**Comment by VictorTzeng** [comment]
谢谢，已采纳

**Comment by wannvmi** [comment]
`DistributedCacheManager.SetAsync(key, returnValue, Expiration )`
这个好像也错了 ,csredis 的是秒，memorycache是分钟 
`Expiration * 60`  才是对的
ps: 我很疑惑为什么 用dynamic 就能返回值，object 就不能，debug 时候明明都有值的
难道 dynamic 用的是JIT，而object 用的是 CIL？

**Comment by VictorTzeng** [comment]
应该是这个理，空了查查资料。大兄弟如果有答案，还望不吝赐教
